version: '3'

services:
  gateway:
    build: "gateway/"
    ports:
     - "8000:8000"
    depends_on:
     - products
     - users
     - reviews
  products:
    build: "products/"
  users:
    build: "users/"
  reviews:
    build: "reviews/"
