---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
  - port: 8000
  selector:
    app: gateway
