---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
spec:
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: reviews
        image: reviews
---
apiVersion: v1
kind: Service
metadata:
  name: reviews
spec:
  ports:
  - port: 8000
  selector:
    app: reviews
